# Generated by Django 5.2.6 on 2025-09-19 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(db_index=True, max_length=14)),
                ('matricula', models.CharField(db_index=True, max_length=32)),
                ('banco', models.CharField(blank=True, default='', max_length=64)),
                ('stage', models.CharField(choices=[('atendente', 'Atendente'), ('calculista', 'Calculista'), ('atendente_pos_sim', 'Atendente Pós-Sim'), ('gerente_fechamento', 'Gerente Fechamento'), ('atendente_docs', 'Atendente Docs'), ('financeiro', 'Financeiro'), ('contratos_supervisao', 'Contratos/Supervisão')], db_index=True, default='atendente', max_length=32)),
                ('simulacao_status', models.CharField(blank=True, choices=[('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], max_length=16, null=True)),
                ('simulacao_notes', models.TextField(blank=True, default='')),
                ('gerente_notes', models.TextField(blank=True, default='')),
                ('financeiro_notes', models.TextField(blank=True, default='')),
                ('contrato_formalizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_assigned', to=settings.AUTH_USER_MODEL)),
                ('owner_atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, default='', max_length=32)),
                ('to_stage', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='atendimentos.atendimento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['stage', 'created_at'], name='atendimento_stage_518668_idx'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.UniqueConstraint(fields=('cpf', 'matricula'), name='uniq_cpf_matricula'),
        ),
    ]
