# Generated by Django 4.2.24 on 2025-09-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atendimentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atendimento",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atend_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="banco",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="cpf",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="matricula",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="owner_atendente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atend_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="simulacao_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="stage",
            field=models.CharField(
                choices=[
                    ("esteira_global", "Esteira Global"),
                    ("atendente", "Atendente"),
                    ("calculista", "Calculista"),
                    ("atendente_pos_sim", "Atendente (Pós-Sim)"),
                    ("gerente_fechamento", "Gerente (Fechamento)"),
                    ("atendente_docs", "Atendente (Docs)"),
                    ("financeiro", "Financeiro"),
                    ("contratos_supervisao", "Contratos/Supervisão"),
                ],
                default="esteira_global",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="atendimentoevent",
            name="from_stage",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="atendimentoevent",
            name="to_stage",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="AtendimentoSimulacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcela", models.DecimalField(decimal_places=2, max_digits=12)),
                ("coeficiente", models.DecimalField(decimal_places=7, max_digits=10)),
                ("saldo_devedor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "seguro_banco",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "percentual_co",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("prazo_meses", models.IntegerField(default=0)),
                (
                    "pv_total_financiado",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "valor_liberado",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("valor_liquido", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "custo_consultoria",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "liberado_cliente",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulacoes",
                        to="atendimentos.atendimento",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AtendimentoLancamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=128)),
                ("competencia", models.CharField(help_text="MM/AAAA", max_length=7)),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("origem", models.CharField(default="import", max_length=32)),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos",
                        to="atendimentos.atendimento",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="atendimentolancamento",
            constraint=models.UniqueConstraint(
                fields=("atendimento", "banco", "competencia"),
                name="uniq_atd_banco_comp",
            ),
        ),
    ]
