"""Add custo_consultoria_liquido field to simulations

Revision ID: dfcdc58cc638
Revises: 1463d62d8d70
Create Date: 2025-09-30 13:48:11.164543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfcdc58cc638'
down_revision: Union[str, None] = '1463d62d8d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_rows')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('entidade',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('referencia_competencia',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('importado_em',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('previous_contracts_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index('ix_cases_assigned_at')
        batch_op.drop_index('ix_cases_assigned_user_expires')
        batch_op.drop_index('ix_cases_assignment_expires_at')
        batch_op.drop_index('ix_cases_import_source')
        batch_op.drop_constraint('fk_cases_import_batch', type_='foreignkey')
        batch_op.create_foreign_key(None, 'imports', ['import_batch_id'], ['id'])

    with op.batch_alter_table('payroll_lines', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_consultoria_liquido', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('custo_consultoria_liquido')

    with op.batch_alter_table('payroll_lines', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_cases_import_batch', 'imports', ['import_batch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_cases_import_source', ['source', 'entity_code'], unique=False)
        batch_op.create_index('ix_cases_assignment_expires_at', ['assignment_expires_at'], unique=False)
        batch_op.create_index('ix_cases_assigned_user_expires', ['assigned_user_id', 'assignment_expires_at'], unique=False)
        batch_op.create_index('ix_cases_assigned_at', ['assigned_at'], unique=False)
        batch_op.alter_column('previous_contracts_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('importado_em',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('referencia_competencia',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('entidade',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    op.create_table('import_rows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('matricula', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('parsed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name='import_rows_import_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='import_rows_pkey')
    )
    # ### end Alembic commands ###
