services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lifecalling
      POSTGRES_PASSWORD: lifecalling
      POSTGRES_DB: lifecalling
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: ["5433:5432"]

  api:
    build: 
      context: ./apps/api
      dockerfile: Dockerfile
    depends_on: [db]
    volumes:
      - ./apps/api:/app
      - uploads:/app/uploads
    ports: ["8000:8000"]
    environment:
      - ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=lifecalling
      - POSTGRES_USER=lifecalling
      - POSTGRES_PASSWORD=lifecalling
      - JWT_SECRET=change-me-in-production-min-32-chars
      - JWT_ISS=lifecalling
      - JWT_ACCESS_TTL_SECONDS=3600
      - JWT_REFRESH_TTL_SECONDS=2592000
      - FRONTEND_URL=http://localhost:3000
      - COOKIE_DOMAIN=
      - UPLOAD_DIR=./uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.windows
    depends_on: [api]
    ports: ["3000:3000"]
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NODE_ENV=development

volumes:
  db_data:
  uploads:
