"""Add custo_consultoria_liquido to simulations

Revision ID: 2434c05250b1
Revises: a7e82e0d9f0a
Create Date: 2025-09-30 15:22:50.788487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2434c05250b1'
down_revision: Union[str, None] = 'a7e82e0d9f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_logs_case_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='case_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='case_logs_pkey')
    )
    # ### end Alembic commands ###
