"""add_created_by_created_at_to_clients

Revision ID: 2358a948a557
Revises: 93004d254ff9
Create Date: 2025-12-01 13:44:11.627366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2358a948a557'
down_revision: Union[str, None] = '93004d254ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_clients_created_by', 'clients', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_clients_created_by', 'clients', type_='foreignkey')
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'created_by')
    # ### end Alembic commands ###
