"""add_mobile_simulation_multibank_fields

Revision ID: 261c0a8e5d26
Revises: b1c2d3e4f5g6
Create Date: 2025-11-21 09:29:17.557434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261c0a8e5d26'
down_revision: Union[str, None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contracts_imposto_expense_id')

    with op.batch_alter_table('external_client_incomes', schema=None) as batch_op:
        batch_op.drop_index('ix_external_income_created_by')

    with op.batch_alter_table('mobile_simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banks_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('prazo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coeficiente', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seguro', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('percentual_consultoria', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_simulations', schema=None) as batch_op:
        batch_op.drop_column('percentual_consultoria')
        batch_op.drop_column('seguro')
        batch_op.drop_column('coeficiente')
        batch_op.drop_column('prazo')
        batch_op.drop_column('banks_json')

    with op.batch_alter_table('external_client_incomes', schema=None) as batch_op:
        batch_op.create_index('ix_external_income_created_by', ['created_by'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contracts_imposto_expense_id', ['imposto_expense_id'], unique=False)

    # ### end Alembic commands ###
