"""add_agent_to_finance_expenses

Revision ID: 792d3dd3313c
Revises: a1b2c3d4e5f6
Create Date: 2025-10-24 10:00:58.858357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792d3dd3313c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['agent_user_id'], ['id'])

    with op.batch_alter_table('finance_incomes', schema=None) as batch_op:
        batch_op.alter_column('client_cpf',
               existing_type=sa.VARCHAR(length=14),
               comment=None,
               existing_comment='CPF do cliente (para receitas manuais)',
               existing_nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Nome do cliente (para receitas manuais)',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_incomes', schema=None) as batch_op:
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do cliente (para receitas manuais)',
               existing_nullable=True)
        batch_op.alter_column('client_cpf',
               existing_type=sa.VARCHAR(length=14),
               comment='CPF do cliente (para receitas manuais)',
               existing_nullable=True)

    with op.batch_alter_table('finance_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_name')
        batch_op.drop_column('client_cpf')
        batch_op.drop_column('agent_user_id')

    # ### end Alembic commands ###
