"""add_document_fields_to_mobile_simulations

Revision ID: a8452ce612ad
Revises: 261c0a8e5d26
Create Date: 2025-11-21 09:40:02.964506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8452ce612ad'
down_revision: Union[str, None] = '261c0a8e5d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('document_filename', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_simulations', schema=None) as batch_op:
        batch_op.drop_column('document_filename')
        batch_op.drop_column('document_type')
        batch_op.drop_column('document_url')

    # ### end Alembic commands ###
